# Generated by Django 5.1.1 on 2024-09-29 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Наименование')),
                ('uncrewed_spacecraft', models.CharField(blank=True, max_length=127, verbose_name='АМС')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус (активен)')),
                ('scheduled_at', models.DateField(blank=True, null=True, verbose_name='Запланированная дата')),
                ('image_url', models.URLField(verbose_name='URL к изображению')),
            ],
            options={
                'db_table': 'SpaceObject',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата создания заявки')),
                ('space_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.spaceobject')),
            ],
            options={
                'db_table': 'Flight',
            },
        ),
        migrations.CreateModel(
            name='UncrewedSpacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_uncrewed_spacecrafts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Модератор', to=settings.AUTH_USER_MODEL)),
                ('space_objects', models.ManyToManyField(through='lab.Flight', to='lab.spaceobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UncrewedSpacecraft',
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='uncrewed_spacecraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.uncrewedspacecraft'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('uncrewed_spacecraft', 'space_object')},
        ),
    ]
