# Generated by Django 5.1.1 on 2024-10-07 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Космический объект')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус (активен)')),
                ('image_url', models.URLField(verbose_name='URL к изображению')),
            ],
            options={
                'verbose_name': 'Космический объект',
                'verbose_name_plural': 'Космические объекты',
                'db_table': 'object',
            },
        ),
        migrations.CreateModel(
            name='UncrewedSpacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spacecraft_name', models.CharField(max_length=127, verbose_name='Название АМС')),
                ('spacecraft_description', models.TextField(blank=True, null=True, verbose_name='Описание АМС')),
                ('scheduled_at', models.DateField(blank=True, null=True, verbose_name='Запланированная дата')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_spacecrafts', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spacecrafts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Автоматическая межпланетная станция',
                'verbose_name_plural': 'Автоматические межпланетные станции',
                'db_table': 'spacecraft',
            },
        ),
        migrations.CreateModel(
            name='FlightSpaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата создания заявки')),
                ('space_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spacecrafts', to='lab2.spaceobject')),
                ('spacecraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_objects', to='lab2.uncrewedspacecraft')),
            ],
            options={
                'verbose_name': 'Объект полёта',
                'verbose_name_plural': 'Объекты полёта',
                'db_table': 'spacecraft_spaceobject',
                'unique_together': {('spacecraft', 'space_object')},
            },
        ),
    ]
